import { useEffect, useState } from "react";
import { Alert, Spinner } from "flowbite-react";

import t from "../../utils/translation";
import { credentialsValue, host } from "../../App";

export default function HomeScreen() {
  const [error, setError] = useState<string | null>(null);
  const [welcome, setWelcome] = useState<string | null>(null);

  // fetch welcome message
  useEffect(() => {
    fetch(host + "/api/misc/welcome", { credentials: credentialsValue })
      .then((response) => {
        if (!response.ok) {
          throw new Error(`Unexpected response (${response.statusText}).`);
        }
        return response.text();
      })
      .then((text) => setWelcome(text))
      .catch(() => setError("Unable to load welcome-message."));
  }, []);

  return (
    <div className="mx-20 mt-4">
      <div className="flex justify-between items-center relative w-full mb-10">
        <h3 className="text-4xl font-bold">{t("Home")}</h3>
      </div>
      {error ? (
        <Alert className="m-2" color="failure" onDismiss={() => setError(null)}>
          {error}
        </Alert>
      ) : null}
      <div className="flex justify-center">
        {welcome ? (
          // this html is trustworthy since it is generated by ourselves
          <div dangerouslySetInnerHTML={{ __html: welcome }} />
        ) : (
          <Spinner size="xl" />
        )}
      </div>
    </div>
  );
}

/* template for drafting the default template
<div class="flex flex-col space-y-2 bg-gray-100 p-5 rounded-xl">
  <h3 class="text-2xl font-bold">Welcome!</h3>
  <p class="text-gray-500">
    This is the default welcome message template. It can be changed by setting the 'WELCOME_MESSAGE_TEMPLATE'-variable.
  </p>
</div>
*/
